# Generated by Django 2.2 on 2021-02-10 20:05

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_design',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[projects.models.validate_hours], verbose_name='Actual design hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_development',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[projects.models.validate_hours], verbose_name='Actual development hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_testing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[projects.models.validate_hours], verbose_name='Actual testing hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_design',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[projects.models.validate_hours], verbose_name='Estimated design hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_development',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[projects.models.validate_hours], verbose_name='Estimated development hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_testing',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[projects.models.validate_hours], verbose_name='Estimated testing hours'),
        ),
    ]
